add_subdirectory(${CMAKE_SOURCE_DIR}/Engine/Packages/detex EXCLUDE_FROM_ALL)
set_target_properties(detex PROPERTIES
    MAP_IMPORTED_CONFIG_DEBUG RELEASE
    MAP_IMPORTED_CONFIG_RELWITHDEBINFO RELEASE
)